name: build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: |
          sudo apt update -y
          sudo apt install -y openmpi-bin libopenmpi-dev libnetcdf-dev libnetcdff-dev environment-modules
      
      - name: Build
        run: |
          source /etc/profile.d/modules.sh
          
          export MPICC=mpicc
          export MPIF90=mpif90
          export FC=mpif90
          export CC=mpicc
          
          export NETCDF_INC=$(nc-config --includedir)
          export NETCDF_LIB=$(nc-config --libdir)
          export NETCDFF_INC=$(nf-config --includedir)
          export NETCDFF_LIB=$(nf-config --libdir)
          
          ls -l
          which mpicc
          which mpif90
          nc-config --version
          nf-config --version

          #Compilation
          #
          cd src/chief/
          ln -sf read_wind_input_arno.f90     read_wind_input.f90
          ln -sf read_topo_input_arno.f90     read_topo_input.f90
          ln -sf read_current_input_arno.f90  read_current_input.f90
          ln -sf read_boundary_input_arno.f90 read_boundary_input.f90
          ln -sf read_ice_input_arno.f90      read_ice_input.f90
          #ls -l

          cd ../preproc/
          ln -sf read_topography_arno.f90     read_topography.f90
          #ls -l

          #deactivate OASIS
          #
          cd ../mod/
          ln -sf wam_oasis_inactive_module.f90 wam_oasis_module.f90
          #ls -l 
          
          #make
          cd ../../
          make all
          
